service: auction-svc

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action: 
       - "dynamodb:PutItem"
      Resource: 
      # service_name:region:acc_id:table/<table_name>
      # this makes use of serverless-pseudo-params plugin
       - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionsTable

# IaaC for DynamoDB table(s)
resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      # this facilitates changes in AWS Lambda automatically
      - http:
          method: POST
          path: /auction
